config/routes.rb
require 'sidekiq/web'
require 'api/api'

Gitlab::Application.routes.draw do
  #
  # Search
  #
  get 'search' => "search#show"
  get 'search/autocomplete' => "search#autocomplete", as: :search_autocomplete

  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  # Get all keys of user
  get ':username.keys' => 'profiles/keys#get_keys' , constraints: { username: /.*/ }

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web, at: "/admin/sidekiq", as: :sidekiq
  end

  #
  # Global snippets
  #
  resources :snippets do
    member do
      get "raw"
    end
  end
  get "/s/:username" => "snippets#user_index", as: :user_snippets, constraints: { username: /.*/ }

  #
  # Public namespace
  #
  namespace :public do
    resources :services, only: [:index]
    root to: "services#index"
  end

  #
  # Attachments serving
  #
  get 'files/:type/:id/:filename' => 'files#download', constraints: { id: /\d+/, type: /[a-z]+/, filename:  /.+/ }

  #
  # Admin Area
  #
  namespace :admin do
    resources :users, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ } do
      member do
        put :block
        put :unblock
      end
    end

    resources :broadcast_messages, only: [:index, :create, :destroy]
    resource :logs, only: [:show]
    resource :background_jobs, controller: 'background_jobs', only: [:show]
    get "rss_feeds/fetch_posts" => "rss_feeds#fetch_posts"
    resources :rss_feeds
    resources :services, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }, only: [:index, :show] do

    end

    root to: "dashboard#index"
  end

  #
  # Profile Area
  #
  resource :profile, only: [:show, :update] do
    member do
      get :design

      put :reset_private_token
      put :update_username
    end

    scope module: :profiles do
      resource :account, only: [:show, :update]
      resource :notifications, only: [:show, :update]
      resource :password, only: [:new, :create, :edit, :update] do
        member do
          put :reset
        end
      end
      resources :keys
      resources :emails, only: [:index, :create, :destroy]
      resource :avatar, only: [:destroy]
    end
  end

  match "/u/:username" => "users#show", as: :user, constraints: { username: /.*/ }, via: :get



  #
  # Dashboard Area
  #
  resource :dashboard, controller: "dashboard", only: [:show] do

  end
  get 'dashboard/stars' => "dashboard#stars"
  get 'dashboard/analytics' => "dashboard#analytics"
  get 'dashboard/archive' => "dashboard#archive"

  match 'events/mark_above_as_read/:id' => "events#mark_above_as_read", as: :events_mark_above_as_read, via: :put
  post 'events/archive_all' => "events#archive_all", as: :events_archive_all
  post 'events/undo_archive_all' => "events#undo_archive_all", as: :events_undo_archive_all
  resources :events do
    member do
      post :favorite
      post :unfavorite
    end
  end
  #resources :projects, constraints: { id: /[^\/]+/ }, only: [:new, :create]

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks, registrations: :registrations , passwords: :passwords}
  get 'services/test' => "services#test"
  get 'services/rssfeeds/:id' => "rssfeeds#add_rss_feed"
  get 'rssfeeds/rss' => "rssfeeds#rss"
  post 'rssfeeds/create_rss' => "rssfeeds#create_rss"
  post 'rssfeeds/apply_import' => "rssfeeds#apply_import"
  post 'rssfeeds/add_feed' => "rssfeeds#add_feed"
  post 'rssfeeds/delete_feed/:id' => "rssfeeds#delete_feed", as: :rssfeeds_delete_feed
  resources :services do

  end
  scope 'services' do
    resources :rssfeeds, only: [:update, :destroy] do

    end
  end
  controller :services do
    scope "/users/auth", :as => "auth" do
      get ':provider/callback' => :create
      get :failure
    end
  end
  resource :wall, only: [:show], constraints: {id: /\d+/} do
    member do
      get 'notes'
    end
  end

  resources :notes, only: [:index, :create, :destroy, :update], constraints: {id: /\d+/} do
    member do
      delete :delete_attachment
    end

    collection do
      post :preview
    end
  end
  root to: "dashboard#show"
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  def index
    @services = Service.order("created_at DESC").limit(15)
    @users = User.order("created_at DESC").limit(15)
    @rss_feeds = RssFeed.all
    #@groups = Group.order("created_at DESC").limit(10)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  respond_to :html

  before_filter :load_services
  before_filter :event_filter, only: [:show, :archive]
  before_filter :check_last_events, only: :show


  def show
    @title = 'Dashboard'
    @events = Event.load_events(current_user.id)
    @events = @event_filter.apply_filter(@events,current_user.id)
    @events = @events.limit(50).offset(params[:offset] || 0)
    @note = Note.new
    @events_all_unread_count = 0
    if (params[:offset] == "0" || params[:offset].nil?) && @events.first
      cookies['lasted_event_id'] = @events.first.id
      @events_all_unread_count = Event.where(user_id: current_user.id, action: Event::UNREAD).count
    end

    respond_to do |format|
      format.html
      format.json { pager_json("events/_events", @events.count) }
    end
  end

  def archive
    @title = 'Archive'
    @events = Event.load_archive_events(current_user.id)
    @events = @event_filter.apply_filter(@events,current_user.id)
    @events = @events.limit(50).offset(params[:offset] || 0)
    @note = Note.new
    if params[:offset] == "0" && @events.first
      cookies['lasted_event_id'] = @events.first.id
    end

    respond_to do |format|
      format.html
      format.json { pager_json("events/_events", @events.count) }
    end
  end

  def stars
    filters = cookies['event_star_filter'].split(',') if cookies['event_star_filter'].present?
    @event_filter ||= EventStarFilter.new(filters)
    @title = 'Stars'
    @events = Event.load_star_events(current_user.id)
    @events = @event_filter.apply_star_filter(@events)
    @events = @events.limit(50).offset(params[:offset] || 0)
    respond_to do |format|
      format.html
      format.json { pager_json("events/_events", @events.count) }
    end
  end

  def analytics
    @title = 'Analytics'
    respond_to do |format|
      format.html
      format.js do
        fetch_graph
      end
    end
  end
  def fetch_graph
    @log = Event.graph_log(current_user.id).to_json
    @success = true

  end

  protected

  def load_services
    # Fetch only 30 services.
    # If user needs more - point to Dashboard#services page
    @services = current_user.services

    @services_limit = 30
    @has_authorized_services = @services.count > 0
    @services_count = @services.count

    @publicish_service_count = 1
  end

  def check_last_events
    @last_unread_count = 0
    @last_read_time = Time.now
    if params[:offset] == "0" || params[:offset].nil?
      current_user.services.each do |service|
        if @last_read_time > service.last_read_time
          @last_read_time = service.last_read_time
        end
        @last_unread_count += service.last_unread_count
      end
      if params[:offset] == "0" && Time.now.to_i - current_user.services.first.last_activity_at.to_time.to_i >= 90
        Service.where(user_id: current_user.id).update_all(last_activity_at: Time.now, last_unread_count: 0, last_read_time: Time.now)
        ServicePullWorker.perform_async(nil, current_user.id)
      end
    end
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def filter_path(entity, options={})
    exist_opts = {
      state: params[:state],
      scope: params[:scope],
      project_id: params[:project_id],
    }

    options = exist_opts.merge(options)

    path = request.path
    path << "?#{options.to_param}"
    path
  end

  def entities_per_project(project, entity)
    case entity.to_sym
    when :issue then @issues.where(project_id: project.id)
    when :merge_request then @merge_requests.where(target_project_id: project.id)
    else
      []
    end.count
  end

  def projects_dashboard_filter_path(options={})
    exist_opts = {
      sort: params[:sort],
      scope: params[:scope],
      group: params[:group],
    }

    options = exist_opts.merge(options)

    path = request.path
    path << "?#{options.to_param}"
    path
  end

  def service_name(service)
    case service.service_name
      when 'RssFeedService'
        feed = RssFeed.find(service.access_token)
        return feed.name
      else
        return service.provider
    end
  end

  def service_avatar(service)
    case service.service_name
      when 'RssFeedService'
        author = Author.where(provider: service.access_token).first
        return author.avatar unless author.nil?
      else
        return image_path("services/#{service.provider}.png")
    end
  end
end

app/views/dashboard/_activities.html.haml
- if @events.any?
  .content_list
- else
  .nothing-here-block
    No service activity currently

= spinner

app/views/dashboard/_service.html.haml
= link_to "#", class: "event_service_filter_link", id: "#{service.id}_event_filter" do
  .dash-project-access-icon
    = image_tag service_avatar(service)
  %span.str-truncated
    %span.namespace-name
      - if service.service_name != 'RssFeedService'
        = service.info.name
        \/
    %span.project-name.filter-title
      = service_name(service)

app/views/dashboard/_services.html.haml
.panel.panel-default.ui-box
  .panel-heading.title.clearfix
    = search_field_tag :filter_services, nil, placeholder: 'Filter by name', class: 'dash-filter form-control'
    - if current_user.can_create_project?
      %span.pull-right
        = link_to new_service_path, class: "btn btn-new" do
          %i.icon-plus
          New service

  %ul.well-list.dash-list
    - services.each do |service|
      %li.project-row
        = render "service", service: service

    - if services.blank?
      %li
        .nothing-here-block There are no services here.

app/views/dashboard/_sidebar.html.haml
%ul.nav.nav-tabs.dash-sidebar-tabs
  %li.active
    = link_to '#services', 'data-toggle' => 'tab', id: 'sidebar-services-tab' do
      Services
      %span.badge= @services.count
  %li
    = link_to '#gloablchat', 'data-toggle' => 'tab', id: 'sidebar-gloablchat-tab' do
      Join the chat


.tab-content
  .tab-pane.active#services
    = render "services", services: @services
    .prepend-top-20
      %span
        = link_to "javascript:void(0)", class: "has_tooltip cgray", id: 'sidebar-clear-filter', 'data-original-title' => 'Will reload all posts.' do
          %i.icon-remove
          %strong Clear filter
        &nbsp;
        - if params[:action] == "show" && @events_all_unread_count >= 1
          = link_to "javascript:void(0)", class: "has_tooltip cgray", id: 'sidebar-archive-all', :'data-path' => events_archive_all_path, 'data-original-title' => 'Move all your unread posts to archive folder.' do
            %i.icon-check
            %strong Archive all
  .tab-pane#gloablchat
    = render "notes/index"

app/views/dashboard/_zero_authorized_projects.html.haml
%h3.page-title Welcome to poqbod!
%hr
%div
  .dashboard-intro-icon
    %i.icon-bookmark-empty
  %div
    %p.slead
      You don't have access to any service right now.
      %br
      - if current_user.can_create_project?
        You can create up to
        %strong= pluralize(current_user.projects_limit, "service") + "."
        Click on the button below to add a new one
      - else
        If you are added to a project, it will be displayed here

    - if current_user.can_create_project?
      .link_holder
        = link_to new_service_path, class: "btn btn-new" do
          New service »

app/views/dashboard/analytics.html.haml
- if @has_authorized_services
  .loading-graph
    %center
      %h3.page-title
        %i.icon-spinner.icon-spin
        Building analytics graph.
      %p Please wait a moment, this page will automatically refresh when ready.

  .stat-graph
    .header.clearfix
      %h3#date_header.page-title
      %p.light
        Your block,read,star analytics
      %input#brush_change{:type => "hidden"}
    .graphs
      #read-analytics

  :javascript
    $(".stat-graph").hide();

    $.ajax({
      type: "GET",
      url: location.href,
      complete: function() {
        $(".stat-graph").show();
        $(".loading-graph").hide();

        controller = new ReadAnalyticsStatGraph();
        controller.init($('#brush_change').val());
      },
      dataType: "script"
    });

- else
  = render "zero_authorized_projects"

app/views/dashboard/analytics.js.haml
- if @success
  :plain
    $('#brush_change').val(JSON.stringify(#{@log}))
- else
  :plain
    $('.stat-graph').replaceWith('<div class="alert alert-danger">Failed to load graph</div>')

app/views/dashboard/archive.html.haml
- if @has_authorized_services
  .dashboard.row
    .activities.col-md-8
      = render 'activities'
    .side.col-md-4.hidden-sm.hidden-xs
      #dashboard_sidebar
        = render 'sidebar'

- else
  = render "zero_authorized_projects"

app/views/dashboard/show.html.haml
- if @has_authorized_services
  .dashboard.row
    .activities.col-md-8
      = render 'activities'
    .side.col-md-4.hidden-sm.hidden-xs
      #dashboard_sidebar
        = render 'sidebar'

- else
  = render "zero_authorized_projects"

app/views/dashboard/stars.html.haml
- if @has_authorized_services
  .dashboard.row
    .activities.col-md-12
      = render 'shared/event_star_filter'
      - if @events.any?
        .content_list
      - else
        .nothing-here-block
          Your favorite content will appear here, but now it is zero.

      = spinner

- else
  = render "zero_authorized_projects"