config/routes.rb
require 'sidekiq/web'
require 'api/api'

Gitlab::Application.routes.draw do
  #
  # Search
  #
  get 'search' => "search#show"
  get 'search/autocomplete' => "search#autocomplete", as: :search_autocomplete

  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  # Get all keys of user
  get ':username.keys' => 'profiles/keys#get_keys' , constraints: { username: /.*/ }

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web, at: "/admin/sidekiq", as: :sidekiq
  end

  #
  # Global snippets
  #
  resources :snippets do
    member do
      get "raw"
    end
  end
  get "/s/:username" => "snippets#user_index", as: :user_snippets, constraints: { username: /.*/ }

  #
  # Public namespace
  #
  namespace :public do
    resources :services, only: [:index]
    root to: "services#index"
  end

  #
  # Attachments serving
  #
  get 'files/:type/:id/:filename' => 'files#download', constraints: { id: /\d+/, type: /[a-z]+/, filename:  /.+/ }

  #
  # Admin Area
  #
  namespace :admin do
    resources :users, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ } do
      member do
        put :block
        put :unblock
      end
    end

    resources :broadcast_messages, only: [:index, :create, :destroy]
    resource :logs, only: [:show]
    resource :background_jobs, controller: 'background_jobs', only: [:show]
    get "rss_feeds/fetch_posts" => "rss_feeds#fetch_posts"
    resources :rss_feeds
    resources :services, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }, only: [:index, :show] do

    end

    root to: "dashboard#index"
  end

  #
  # Profile Area
  #
  resource :profile, only: [:show, :update] do
    member do
      get :design

      put :reset_private_token
      put :update_username
    end

    scope module: :profiles do
      resource :account, only: [:show, :update]
      resource :notifications, only: [:show, :update]
      resource :password, only: [:new, :create, :edit, :update] do
        member do
          put :reset
        end
      end
      resources :keys
      resources :emails, only: [:index, :create, :destroy]
      resource :avatar, only: [:destroy]
    end
  end

  match "/u/:username" => "users#show", as: :user, constraints: { username: /.*/ }, via: :get



  #
  # Dashboard Area
  #
  resource :dashboard, controller: "dashboard", only: [:show] do

  end
  get 'dashboard/stars' => "dashboard#stars"
  get 'dashboard/analytics' => "dashboard#analytics"
  get 'dashboard/archive' => "dashboard#archive"

  match 'events/mark_above_as_read/:id' => "events#mark_above_as_read", as: :events_mark_above_as_read, via: :put
  post 'events/archive_all' => "events#archive_all", as: :events_archive_all
  post 'events/undo_archive_all' => "events#undo_archive_all", as: :events_undo_archive_all
  resources :events do
    member do
      post :favorite
      post :unfavorite
    end
  end
  #resources :projects, constraints: { id: /[^\/]+/ }, only: [:new, :create]

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks, registrations: :registrations , passwords: :passwords}
  get 'services/test' => "services#test"
  get 'services/rssfeeds/:id' => "rssfeeds#add_rss_feed"
  get 'rssfeeds/rss' => "rssfeeds#rss"
  post 'rssfeeds/create_rss' => "rssfeeds#create_rss"
  post 'rssfeeds/apply_import' => "rssfeeds#apply_import"
  post 'rssfeeds/add_feed' => "rssfeeds#add_feed"
  post 'rssfeeds/delete_feed/:id' => "rssfeeds#delete_feed", as: :rssfeeds_delete_feed
  resources :services do

  end
  scope 'services' do
    resources :rssfeeds, only: [:update, :destroy] do

    end
  end
  controller :services do
    scope "/users/auth", :as => "auth" do
      get ':provider/callback' => :create
      get :failure
    end
  end
  resource :wall, only: [:show], constraints: {id: /\d+/} do
    member do
      get 'notes'
    end
  end

  resources :notes, only: [:index, :create, :destroy, :update], constraints: {id: /\d+/} do
    member do
      delete :delete_attachment
    end

    collection do
      post :preview
    end
  end
  root to: "dashboard#show"
end

app/models/rss_feed.rb
# == Schema Information
#
# Table name: rss_feeds
#
#

class RssFeed < ActiveRecord::Base

  attr_accessible :name, :url, :last_fetched, :status, :last_fetched_id

  validates_uniqueness_of :name
  validates_uniqueness_of :url

  has_many :rss_feeds_rss_categories, dependent: :destroy
  has_many :rss_categories, through: :rss_feeds_rss_categories

  STATUS = { green: 0, yellow: 1, red: 2, block: 3 }
  MIN_YEAR = 1970

  def self.list
    RssFeed.all
  end

  def self.fetch(id)
    RssFeed.find(id)
  end

  def self.fetch_by_ids(ids)
    RssFeed.where(id: ids)
  end

  def self.update_last_fetched(feed, timestamp)
    if self.valid_timestamp?(timestamp, feed.last_fetched)
      feed.last_fetched = timestamp
      feed.status = :green
      feed.save
    end
  end

  def self.delete(feed_id)
    RssFeed.destroy(feed_id)
  end

  def self.set_status(status, feed)
    feed.status = status
    feed.save
  end

  def status
    STATUS.key(read_attribute(:status))
  end

  def status=(s)
    write_attribute(:status, STATUS[s])
  end

  def status_bubble
    return :yellow if status == :red && stories.any?
    status
  end

  def unread_stories
    stories.where('is_read = ?', false)
  end

  def has_unread_stories
    unread_stories.any?
  end

  def post_count
    Post.where(provider: id).count
  end

  def user_count
    Service.where(access_token: id).count
  end

  private

  def self.valid_timestamp?(new_timestamp, current_timestamp)
    new_timestamp && new_timestamp.year >= MIN_YEAR &&
        (current_timestamp.nil? || new_timestamp > current_timestamp)
  end

end

app/controllers/admin/rss_feeds_controller.rb
class Admin::RssFeedsController < Admin::ApplicationController

  def index

    @rss_feeds_rss_categories = RssFeedsRssCategory.list
    @feeds = RssFeed.list

  end

  def new

  end

  def create

  end

  def fetch_posts
    FetchFeedWorker.perform_async
    redirect_to admin_rss_feeds_path
  end

end

app/controllers/rssfeeds_controller.rb
class RssfeedsController < ApplicationController
  before_filter :set_title, only: [:index, :new, :add_rss_feed, :edit, :update]

  respond_to :html

  def index
    @services = current_user.services
  end
  def new
    @services = current_user.services
    @feeds = RssFeed.list
    @rss_categories = RssCategory.parent_category
  end

  def edit

  end
  def rss
    @title = 'RSS'
    @feed = RssFeed.new
  end

  def create_rss

  end

  def update
    @rss_child_categories = RssCategory.child_category(params[:id])
    if params[:service].present? && params[:service][:select_feed].present?
      cids = [params[:id],params[:service][:select_feed]]
    else
      cids = RssCategory.child_category(params[:id]).pluck(:id)
      cids += [params[:id]]
    end
    rss_feed_ids = RssFeedsRssCategory.get_rss_feeds_by_cid(cids).pluck(:id)
    rss_feeds = RssFeed.where(id: rss_feed_ids)
    current_user_services = Service.unscoped.where(user_id: current_user.id, active: [0,1])
    if current_user_services.any?{|service| service.provider == params[:id].to_s}
      if params[:service].present? && params[:service][:select_feed].present?
        Service.unscoped.where(user_id: current_user.id, active: [0,1], provider: params[:id]).update_all(active: 0)
        if current_user_services.any?{|service| service.nickname == params[:service][:select_feed].to_s}
          Service.unscoped.where(user_id: current_user.id, active: [0,1], nickname: params[:service][:select_feed]).update_all(active: 1)
        else
          save_service(rss_feeds)
        end
      else
        Service.unscoped.where(user_id: current_user.id, active: [0,1], provider: params[:id]).update_all(active: 1)
      end
    else
      save_service(rss_feeds)
    end
    flash[:notice] = 'Service was successfully saved.'
    redirect_to "/services/rssfeeds/#{params[:id]}"
  end

  def add_rss_feed
    @rss_category = RssCategory.find(params[:id])
    @rss_child_categories = RssCategory.child_category(params[:id])
    @service = Service.new
    @rssfeed = RssFeed.new
    if current_user.services.any?{|service_item| service_item.provider == @rss_category.id.to_s}
      service_item = Service.where(user_id: current_user.id, provider: params[:id]).first
      @service.id = params[:id]
      @service.nickname = service_item.nickname
    else
      @service.nickname = "5"
    end

  end

  def add_feed
    @feed_url = params[:feed_url]
    @feed_group = params[:feed_group]
    feed = AddNewFeed.add(@feed_url, current_user, @feed_group)

    if feed == 0
      flash[:alert] = 'Feed already subscribed'
      render text: 2
    elsif feed
      flash[:notice] = 'Feed successfully added'
      render text: 1
    else
      flash[:alert] = 'Feed not found'
      render text: 3
    end
  end

  def delete_feed
    Service.unscoped.where(user_id: current_user.id, access_token: params[:id]).update_all(active: 0)
    flash[:notice] = 'Feed successfully removed'
    render text: 1
  end

  def apply_import
    tmpfile = TmpFile.new
    tmpfile.note = params["opml_file"].read
    tmpfile.user_id = current_user.id
    tmpfile.save
    ImportOpmlWorker.perform_async(tmpfile.id)
    #ImportFromOpml.import(params["opml_file"].read, current_user)
    flash[:notice] = 'Please wait a minute until the importer worker is finished.'
    redirect_to new_service_url
  end

  def destroy
    Service.unscoped.where(user_id: current_user.id, provider: params[:id]).update_all(active: 0)
    flash[:notice] = 'Successfully removed service.'
    redirect_to new_service_url
  end

  private
  def set_title
    @title = 'Service'
  end

  def save_service(rss_feeds)
    rss_feeds.each do |feed|
      service = Service.new
      service.service_name = 'RssFeedService'
      service.uid = current_user.id.to_s + "_" + feed.id.to_s
      service.access_token = feed.id
      service.provider = params[:id]
      if params[:service].present? && params[:service][:select_feed].present?
        service.nickname = params[:service][:select_feed]
      end
      service.user = current_user
      service.active = 1
      service.last_activity_at = Time.now
      service.last_read_time = Time.now
      service.last_unread_count = 0
      service.save
      ServicePullWorker.perform_async(service.id)
    end
  end
end

app/views/admin/rss_feeds/_form.html.haml
.user_new
  = form_for [:admin, @user], html: { class: 'form-horizontal' } do |f|
    -if @user.errors.any?
      #error_explanation
        %ul.unstyled.alert.alert-danger
          - @user.errors.full_messages.each do |msg|
            %li= msg

    %fieldset
      %legend Account
      .form-group
        = f.label :name, class: 'control-label'
        .col-sm-10
          = f.text_field :name, required: true, autocomplete: "off", class: 'form-control'
          %span.help-inline * required
      .form-group
        = f.label :username, class: 'control-label'
        .col-sm-10
          = f.text_field :username, required: true, autocomplete: "off", class: 'form-control'
          %span.help-inline * required
      .form-group
        = f.label :email, class: 'control-label'
        .col-sm-10
          = f.text_field :email, required: true, autocomplete: "off", class: 'form-control'
          %span.help-inline * required

    .form-actions
      - if @user.new_record?
        = f.submit 'Create user', class: "btn btn-create"
        = link_to 'Cancel', admin_users_path, class: "btn btn-cancel"
      - else
        = f.submit 'Save changes', class: "btn btn-save"
        = link_to 'Cancel', admin_user_path(@user), class: "btn btn-cancel"

app/views/admin/rss_feeds/edit.html.haml
%h3.page-title
  #{@user.name} &rarr;
  %i.icon-edit
  Edit user
%hr
= render 'form'

app/views/admin/rss_feeds/index.html.haml
.row
  .col-md-12
    .ui-box
      .title
        Feeds (#{@feeds.count}) Posts (#{Post.rss_count})
        .pull-right
          Category | Subscribers | Posts | Last Fetch Time
      %ul.well-list
        - @rss_feeds_rss_categories.each do |feed|
          %li
            .list-item-name
              = feed.rss_feed.name
            .pull-right
              %span.light
                = feed.rss_category.name + " | " + feed.rss_feed.user_count.to_s + " | " + feed.rss_feed.post_count.to_s + " | " + feed.rss_feed.last_fetched.stamp('05/14/2014 12:13PM')

app/views/admin/rss_feeds/new.html.haml
%h3.page-title
  %i.icon-plus
  New Feed
%hr
= render 'form'

app/views/admin/rss_feeds/show.html.haml
%h3.page-title
  %span.cgray User:
  = @user.name
  - if @user.blocked?
    %span.cred (Blocked)
  - if @user.admin
    %span.cred (Admin)

  .pull-right
    = link_to edit_admin_user_path(@user), class: "btn btn-grouped" do
      %i.icon-edit
      Edit
%hr

.row
  .col-md-6
    .ui-box
      .title
        Account:
        .pull-right
          = image_tag avatar_icon(@user.email, 32), class: "avatar s32"
      %ul.well-list
        %li
          %span.light Name:
          %strong= @user.name
        %li
          %span.light Username:
          %strong
            = @user.username
        %li
          %span.light Email:
          %strong
            = mail_to @user.email
        %li
          %span.light Can create groups:
          %strong
            = @user.can_create_group ? "Yes" : "No"
        %li
          %span.light Personal services limit:
          %strong
            = @user.projects_limit
        %li
          %span.light Member since:
          %strong
            = @user.created_at.stamp("Nov 12, 2031")
        - if @user.confirmed_at
          %li
            %span.light Confirmed at:
            %strong
              = @user.confirmed_at.stamp("Nov 12, 2031")
        - else
          %li
            %span.light Confirmed:
            %strong.cred
              No

        %li
          %span.light Last sign-in at:
          %strong
            - if @user.last_sign_in_at
              = @user.last_sign_in_at.stamp("Nov 12, 2031")
            - else
              never

        - if @user.ldap_user?
          %li
            %span.light LDAP uid:
            %strong
              = @user.extern_uid

        - if @user.created_by
          %li
            %span.light Created by:
            %strong
              = link_to @user.created_by.name, [:admin, @user.created_by]

    - unless @user == current_user
      - if @user.blocked?
        .alert.alert-info
          %h4 This user is blocked
          %p Blocking user has the following effects:
          %ul
            %li User will not be able to login
            %li User will not be able to access git repositories
            %li User will be removed from joined projects and groups
            %li Personal projects will be left
            %li Owned groups will be left
          %br
          = link_to 'Unblock user', unblock_admin_user_path(@user), method: :put, class: "btn btn-new", data: { confirm: 'Are you sure?' }
      - else
        .alert.alert-warning
          %h4 Block this user
          %p Blocking user has the following effects:
          %ul
            %li User will not be able to login
            %li User will not be able to access git repositories
            %li User will be removed from joined projects and groups
            %li Personal projects will be left
            %li Owned groups will be left
          %br
          = link_to 'Block user', block_admin_user_path(@user), data: { confirm: 'USER WILL BE BLOCKED! Are you sure?' }, method: :put, class: "btn btn-remove"

      .alert.alert-danger
        %h4
          Remove user
        %p Deleting a user has the following effects:
        %ul
          %li All user content like authored posts, snippets, comments will be removed
          - rp = @user.services.count
          - unless rp.zero?
            %li #{pluralize rp, 'personal project'} will be removed and cannot be restored
        %br
        = link_to 'Remove user', [:admin, @user], data: { confirm: "USER #{@user.name} WILL BE REMOVED! Are you sure?" }, method: :delete, class: "btn btn-remove"

    .ui-box
      .title Services (#{@services.count})
      %ul.well-list
        - @services.each do |project|
          %li.users_project
            = link_to "#", class: dom_class(project) do
              = project.provider