config/routes.rb
require 'sidekiq/web'
require 'api/api'

Gitlab::Application.routes.draw do
  #
  # Search
  #
  get 'search' => "search#show"
  get 'search/autocomplete' => "search#autocomplete", as: :search_autocomplete

  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  # Get all keys of user
  get ':username.keys' => 'profiles/keys#get_keys' , constraints: { username: /.*/ }

  constraint = lambda { |request| request.env["warden"].authenticate? and request.env['warden'].user.admin? }
  constraints constraint do
    mount Sidekiq::Web, at: "/admin/sidekiq", as: :sidekiq
  end

  #
  # Global snippets
  #
  resources :snippets do
    member do
      get "raw"
    end
  end
  get "/s/:username" => "snippets#user_index", as: :user_snippets, constraints: { username: /.*/ }

  #
  # Public namespace
  #
  namespace :public do
    resources :services, only: [:index]
    root to: "services#index"
  end

  #
  # Attachments serving
  #
  get 'files/:type/:id/:filename' => 'files#download', constraints: { id: /\d+/, type: /[a-z]+/, filename:  /.+/ }

  #
  # Admin Area
  #
  namespace :admin do
    resources :users, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ } do
      member do
        put :block
        put :unblock
      end
    end

    resources :broadcast_messages, only: [:index, :create, :destroy]
    resource :logs, only: [:show]
    resource :background_jobs, controller: 'background_jobs', only: [:show]
    get "rss_feeds/fetch_posts" => "rss_feeds#fetch_posts"
    resources :rss_feeds
    resources :services, constraints: { id: /[a-zA-Z.\/0-9_\-]+/ }, only: [:index, :show] do

    end

    root to: "dashboard#index"
  end

  #
  # Profile Area
  #
  resource :profile, only: [:show, :update] do
    member do
      get :design

      put :reset_private_token
      put :update_username
    end

    scope module: :profiles do
      resource :account, only: [:show, :update]
      resource :notifications, only: [:show, :update]
      resource :password, only: [:new, :create, :edit, :update] do
        member do
          put :reset
        end
      end
      resources :keys
      resources :emails, only: [:index, :create, :destroy]
      resource :avatar, only: [:destroy]
    end
  end

  match "/u/:username" => "users#show", as: :user, constraints: { username: /.*/ }, via: :get



  #
  # Dashboard Area
  #
  resource :dashboard, controller: "dashboard", only: [:show] do

  end
  get 'dashboard/stars' => "dashboard#stars"
  get 'dashboard/analytics' => "dashboard#analytics"
  get 'dashboard/archive' => "dashboard#archive"

  match 'events/mark_above_as_read/:id' => "events#mark_above_as_read", as: :events_mark_above_as_read, via: :put
  post 'events/archive_all' => "events#archive_all", as: :events_archive_all
  post 'events/undo_archive_all' => "events#undo_archive_all", as: :events_undo_archive_all
  resources :events do
    member do
      post :favorite
      post :unfavorite
    end
  end
  #resources :projects, constraints: { id: /[^\/]+/ }, only: [:new, :create]

  devise_for :users, controllers: { omniauth_callbacks: :omniauth_callbacks, registrations: :registrations , passwords: :passwords}
  get 'services/test' => "services#test"
  get 'services/rssfeeds/:id' => "rssfeeds#add_rss_feed"
  get 'rssfeeds/rss' => "rssfeeds#rss"
  post 'rssfeeds/create_rss' => "rssfeeds#create_rss"
  post 'rssfeeds/apply_import' => "rssfeeds#apply_import"
  post 'rssfeeds/add_feed' => "rssfeeds#add_feed"
  post 'rssfeeds/delete_feed/:id' => "rssfeeds#delete_feed", as: :rssfeeds_delete_feed
  resources :services do

  end
  scope 'services' do
    resources :rssfeeds, only: [:update, :destroy] do

    end
  end
  controller :services do
    scope "/users/auth", :as => "auth" do
      get ':provider/callback' => :create
      get :failure
    end
  end
  resource :wall, only: [:show], constraints: {id: /\d+/} do
    member do
      get 'notes'
    end
  end

  resources :notes, only: [:index, :create, :destroy, :update], constraints: {id: /\d+/} do
    member do
      delete :delete_attachment
    end

    collection do
      post :preview
    end
  end
  root to: "dashboard#show"
end

app/views/shared/_event_filter.html.haml
.event_filter
  = event_filter_link EventFilter.important, 'Important'
  = event_filter_link EventFilter.normal, 'Normal'
  = event_filter_link EventFilter.low, 'Low'

app/views/shared/_event_star_filter.html.haml
.event_filter
  = event_star_filter_link EventStarFilter.posttime, 'Sort by post time'
  = event_star_filter_link EventStarFilter.startime, 'Sort by Star time'

app/views/shared/_file_hljs.html.haml
%div.highlighted-data{class: user_color_scheme_class}
  .line-numbers
    - blob.data.lines.to_a.size.times do |index|
      - offset = defined?(first_line_number) ? first_line_number : 1
      - i = index + offset
      = link_to "#L#{i}", id: "L#{i}", rel: "#L#{i}" do
        %i.icon-link
        = i
  .highlight
    %pre
      %code
        = blob.data

app/views/shared/_filter.html.haml
.side-filters.hidden-xs.hidden-sm
  = form_tag filter_path(entity), method: 'get' do
    - if current_user
      %fieldset.scope-filter
        %ul.nav.nav-pills.nav-stacked
          %li{class: ("active" if params[:scope] == 'assigned-to-me')}
            = link_to filter_path(entity, scope: 'assigned-to-me') do
              Assigned to me
          %li{class: ("active" if params[:scope] == 'authored')}
            = link_to filter_path(entity, scope: 'authored') do
              Created by me
          %li{class: ("active" if params[:scope] == 'all')}
            = link_to filter_path(entity, scope: 'all') do
              Everyone's

    %fieldset.status-filter
      %legend State
      %ul.nav.nav-pills
        %li{class: ("active" if params[:state] == 'opened')}
          = link_to filter_path(entity, state: 'opened') do
            Open
        %li{class: ("active" if params[:state] == 'closed')}
          = link_to filter_path(entity, state: 'closed') do
            Closed
        %li{class: ("active" if params[:state] == 'all')}
          = link_to filter_path(entity, state: 'all') do
            All

    %fieldset
      %legend Projects
      %ul.nav.nav-pills.nav-stacked.nav-small
        - @projects.each do |project|
          - unless entities_per_project(project, entity).zero?
            %li{class: ("active" if params[:project_id] == project.id.to_s)}
              = link_to filter_path(entity, project_id: project.id) do
                = project.name_with_namespace
                %small.pull-right= entities_per_project(project, entity)

    %fieldset
      - if params[:state].present? || params[:project_id].present?
        = link_to filter_path(entity, state: nil, project_id: nil), class: 'pull-right cgray' do
          %i.icon-remove
          %strong Clear filter

app/views/shared/_issues.html.haml
- if @issues.any?
  - @issues.group_by(&:project).each do |group|
    .ui-box.ui-box-small
      - project = group[0]
      .title
        = link_to_project project
        = link_to 'show all', project_issues_path(project), class: 'pull-right'

      %ul.well-list.issues-list
        - group[1].each do |issue|
          = render 'projects/posts/issue', issue: issue
  = paginate @issues, theme: "gitlab"
- else
  .nothing-here-block No posts to show

app/views/shared/_no_ssh.html.haml
- if cookies[:hide_no_ssh_message].blank? && current_user.require_ssh_key? && !current_user.hide_no_ssh_key
  .no-ssh-key-message
    .container
      You won't be able to pull or push project code via SSH until you #{link_to 'add an SSH key', new_profile_key_path} to your profile
      .pull-right.hidden-xs
        = link_to "Don't show again", profile_path(user: {hide_no_ssh_key: true}), method: :put, class: 'hide-no-ssh-message', remote: true
        |
        = link_to 'Remind later', '#', class: 'hide-no-ssh-message'
      .links-xs.visible-xs
        = link_to "Add key", new_profile_key_path
        |
        = link_to "Don't show again", profile_path(user: {hide_no_ssh_key: true}), method: :put, class: 'hide-no-ssh-message', remote: true
        |
        = link_to 'Later', '#', class: 'hide-no-ssh-message'

app/views/shared/_project_filter.html.haml
.side-filters.hidden-xs.hidden-sm
  = form_tag project_entities_path, method: 'get' do
    - if current_user
      %fieldset
        %ul.nav.nav-pills.nav-stacked
          %li{class: ("active" if params[:scope] == 'all')}
            = link_to project_filter_path(scope: 'all') do
              Everyone's
          %li{class: ("active" if params[:scope] == 'assigned-to-me')}
            = link_to project_filter_path(scope: 'assigned-to-me') do
              Assigned to me
          %li{class: ("active" if params[:scope] == 'created-by-me')}
            = link_to project_filter_path(scope: 'created-by-me') do
              Created by me

    %fieldset
      %legend State
      %ul.nav.nav-pills
        %li{class: ("active" if params[:state] == 'opened')}
          = link_to project_filter_path(state: 'opened') do
            Open
        %li{class: ("active" if params[:state] == 'closed')}
          = link_to project_filter_path(state: 'closed') do
            Closed
        %li{class: ("active" if params[:state] == 'all')}
          = link_to project_filter_path(state: 'all') do
            All

    - if defined?(labels)
      %fieldset
        %legend Labels
        %ul.nav.nav-pills.nav-stacked.nav-small.labels-filter
          - issue_label_names.each do |label_name|
            %li{class: label_filter_class(label_name)}
              = link_to labels_filter_path(label_name) do
                %span{class: "label #{label_css_class(label_name)}"}
                  %i.icon-tag
                = label_name
                - if selected_label?(label_name)
                  .pull-right
                    %i.icon-remove

          - if issue_label_names.empty?
            .light-well
              Add first label to your issues
              %br
              or #{link_to 'generate', generate_project_labels_path(@project, redirect: redirect), method: :post} default set of labels

    %fieldset
      - if %w(state scope milestone_id assignee_id label_name).select { |k| params[k].present? }.any?
        = link_to project_entities_path, class: 'cgray pull-right' do
          %i.icon-remove
          %strong Clear filter

app/views/shared/_promo.html.haml
.gitlab-promo
  = link_to "Homepage", "https://www.gitlab.com/"
  = link_to "Blog", "https://www.gitlab.com/blog/"
  = link_to "@gitlabhq", "https://twitter.com/gitlabhq"

app/views/shared/_ref_switcher.html.haml
= form_tag switch_project_refs_path(@project), method: :get, class: "project-refs-form" do
  = select_tag "ref", grouped_options_refs, class: "project-refs-select select2 select2-sm"
  = hidden_field_tag :destination, destination
  - if defined?(path)
    = hidden_field_tag :path, path
  - @options && @options.each do |key, value|
    = hidden_field_tag key, value, id: nil

app/views/shared/_sort_dropdown.html.haml
.dropdown.inline.prepend-left-10
  %a.dropdown-toggle.btn{href: '#', "data-toggle" => "dropdown"}
    %span.light sort:
    - if @sort.present?
      = @sort
    - else
      Newest
    %b.caret
  %ul.dropdown-menu
    %li
      = link_to project_filter_path(sort: 'newest') do
        Newest
      = link_to project_filter_path(sort: 'oldest') do
        Oldest
      = link_to project_filter_path(sort: 'recently_updated') do
        Recently updated
      = link_to project_filter_path(sort: 'last_updated') do
        Last updated
      = link_to project_filter_path(sort: 'milestone_due_soon') do
        Milestone due soon
      = link_to project_filter_path(sort: 'milestone_due_later') do
        Milestone due later